### ISSUE TITLE
Task2 : Foooood

### ISSUE THREAD

**Issue by NirbhayPaliwal** [opencodeiiita/Code-Digger-2023#142]
Steps to solve this problem successfully

- make a file (.cpp or any programming code) containing your code in Task2_Foooood folder in Tasks.

- You have 1 day until the spy gets bored with you and assigns the task to someone else.

- Your PR will not be merged if it contains the Wrong Answer.

**Comment by Apoorv012** [comment]
claim

**Comment by tonyStark-Jr** [comment]
c

**Comment by Rohit-110** [comment]
claim

**Comment by sarthakvermaa** [comment]
claim

**Comment by kushal7201** [comment]
Claim

**Comment by PoonamGate** [comment]
claim

**Comment by shreya0154** [comment]
claim
