### ISSUE TITLE
Task 3: Hollow Pyramid

### ISSUE THREAD

**Issue by agrim317** [opencodeiiita/Code-Digger-2023#143]
### Steps to Solve This Problem Successfully

- The problem statement is located in `Problem.md` within the `Task_3_Hollow_Pyramid` folder. Please follow all the guidelines carefully.

- Create a file containing your solution in any programming language in the `Task_3_Hollow_Pyramid` folder within the `Tasks` directory.

- You have one day before the spy loses interest and reassigns the task to someone else.

- Your pull request (PR) will not be merged if it contains an incorrect answer, and the issue will be reassigned to another contributor.

**Comment by tonyStark-Jr** [comment]
c

**Comment by kushal7201** [comment]
Claim

**Comment by QuantTitan** [comment]
c

**Comment by Jarviss77** [comment]
claim

**Comment by CodinJack** [comment]
claim

**Comment by PoonamGate** [comment]
claim
