### ISSUE TITLE
Task 4 : Unlock

### ISSUE THREAD

**Issue by NirbhayPaliwal** [opencodeiiita/Code-Digger-2023#156]
Steps to solve this problem successfully

make a file (.cpp or any programming code) containing your code in Task4_Unlock folder in Tasks.

You have 1 day until the spy gets bored with you and assigns the task to someone else.

Your PR will not be merged if it contains the Wrong Answer.

**Comment by tonyStark-Jr** [comment]
c

**Comment by sarthakvermaa** [comment]
claim

**Comment by ssugam10** [comment]
claim

**Comment by AngadManroy** [comment]
Claim

**Comment by kushal7201** [comment]
Claim

**Comment by Rohit-110** [comment]
claim

**Comment by vineeshmittal1** [comment]
claim
