### ISSUE TITLE
Debugging Task 1

### ISSUE THREAD

**Issue by agrim317** [opencodeiiita/Code-Digger-2023#200]
### Issue Guidelines

- **Debugging Task:** Debug the code available [here](https://codeforces.com/contest/1846/submission/212583320).
- **Folder Creation:** Create a `Task 1` folder within `Debugs-and-Optimizations`. Inside `Task 1`, add:
  - `explanation.txt`: Explain why the given submission failed.
  - `solution.cpp`: Correct the code without a complete rewrite.
- **Correction Approach:** Make necessary code corrections; refrain from writing an entirely new solution.
- **Deadline:** Complete the task within one day to avoid reassignment.
- **Pull Request (PR) Conditions:** PRs with incorrect answers won't be merged; the issue will be reassigned.

**Comment by sarthakvermaa** [comment]
claim

**Comment by Apoorv012** [comment]
claim

**Comment by rnavaneeth992** [comment]
Claim

**Comment by Rohit-110** [comment]
claim

**Comment by Jarviss77** [comment]
claim

**Comment by Siddharthjoshi2624** [comment]
claim

**Comment by theprocoder2367** [comment]
Claim

**Comment by rndastech** [comment]
claim

**Comment by agrim317** [comment]
This is a 'first-come, first-served' issue and can only be assigned to one person at a time. The issue will become available for claim only if the current assignee fails to submit a PR within 24 hours or submits an incorrect solution.
