### ISSUE TITLE
Task 7: Pavitra's Party

### ISSUE THREAD

**Issue by agrim317** [opencodeiiita/Code-Digger-2023#208]
### Steps to Solve This Problem Successfully

- The problem statement is located in `Problem.md` within the `Task_7_Pavitra's_Party` folder. Please follow all the guidelines carefully.

- This is a competitive task, allowing everyone to submit a PR for this issue. However, only the best PR will be merged. **Points will be awarded only for the correct code with the fewest number of characters**.

- Create a file containing your solution in any programming language and place it in the `Task_7_Pavitra's_Party` folder within the `Tasks` directory.

- You will not earn points if your submission contains an incorrect answer.

- You have 24 hours to submit a PR.

**Comment by Apoorv012** [comment]
c

**Comment by Jarviss77** [comment]
Claim

**Comment by Harshal5167** [comment]
C

**Comment by agrim317** [comment]
Everyone is allowed to submit a PR for this issue but only the correct code with least character count will be merged.

**Comment by MonuGit9** [comment]
Claim
