### ISSUE TITLE
Debugging Task2

### ISSUE THREAD

**Issue by Fremdder** [opencodeiiita/Code-Digger-2023#226]
### Issue Guidelines

- Debugging Task: Debug the code available [here](https://codeforces.com/contest/1721/submission/217068945).

- Folder Creation: Create a Task 2 folder within Debugs-and-Optimizations. Inside Task 2, add:

       1.          explanation.txt: Explain why the given submission failed.

       2.          testcase.txt : on which testcase above code is giving WA

       3.          solution.cpp: Correct the code without a complete rewrite.

- Correction Approach: Make necessary code corrections; refrain from writing an entirely new solution.

- Deadline: Complete the task within one day to avoid reassignment.

- Pull Request (PR) Conditions: PRs with incorrect answers won't be merged; the issue will be reassigned.

**Comment by TheDivineAurora** [comment]
claim

**Comment by sarthakvermaa** [comment]
c

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
Clai.

**Comment by Apoorv012** [comment]
claim

**Comment by sarthakvermaa** [comment]
c

**Comment by kushal7201** [comment]
Claim

**Comment by Jarviss77** [comment]
c

**Comment by poojaindulkar** [comment]
Claim

**Comment by Apoorv012** [comment]
claim

**Comment by DikshantK2004** [comment]
Claim
